# Generated by Django 4.0.3 on 2022-04-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название вида пиломатериала(Для удобного поиска)', max_length=50)),
                ('summary', models.TextField(help_text='Введите краткое описание пиломатериала', max_length=100)),
                ('sizes', models.TextField(help_text='Введите размер пиломатериала', max_length=15)),
                ('num_in_cube', models.FloatField(help_text='Введите количетсво пиломатериала в 1 кубическом метре', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите сорт доски', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название сорта', max_length=50)),
                ('summary', models.CharField(help_text='Введите краткое описание доски', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LumberInstance',
            fields=[
                ('id', models.IntegerField(default=None, help_text='Введите id для этого вида пиломатериала', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(default=None, help_text='Количество пиломатериала')),
                ('status', models.CharField(blank=True, choices=[('д', 'доступно'), ('з', 'зарезервированно'), ('о', 'отсутствует')], default='о', help_text='Доступность пиломатериала', max_length=1)),
                ('lumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.lumber')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='lumber',
            name='types',
            field=models.ManyToManyField(help_text='Выберите вид пиломатериала', to='catalog.types'),
        ),
        migrations.AddField(
            model_name='lumber',
            name='variety',
            field=models.ManyToManyField(help_text='Введите сорт доски', null=True, to='catalog.variety'),
        ),
    ]
