# Generated by Django 4.0.3 on 2022-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lumber_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lumber',
            name='summary',
        ),
        migrations.AlterField(
            model_name='lumber',
            name='title',
            field=models.CharField(help_text='Введите название пиломатериала(Для удобного поиска)', max_length=50),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='types',
            field=models.ManyToManyField(help_text='Выберите сорт пиломатериала', to='catalog.types'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='variety',
            field=models.ManyToManyField(help_text='Выберите вид пиломатериала', to='catalog.variety'),
        ),
    ]
