# Generated by Django 4.0.3 on 2022-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_lumber_summary_alter_lumber_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='title',
            field=models.CharField(help_text='Введите название вида', max_length=50),
        ),
    ]
