# Generated by Django 4.0.3 on 2022-04-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_variety_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lumber',
            name='types',
        ),
        migrations.AddField(
            model_name='lumber',
            name='types',
            field=models.ForeignKey(help_text='Выберите сорт пиломатериала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.types'),
        ),
        migrations.RemoveField(
            model_name='lumber',
            name='variety',
        ),
        migrations.AddField(
            model_name='lumber',
            name='variety',
            field=models.ForeignKey(help_text='Выберите вид пиломатериала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.variety'),
        ),
    ]
