# Generated by Django 4.0.3 on 2022-04-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_lumber_types_lumber_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название цемента(Для удобного поиска)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название металла(Для удобного поиска)', max_length=50)),
                ('sizes', models.TextField(help_text='Введите размер металла', max_length=15)),
                ('width', models.TextField(help_text='Введите толщину металла', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StampCement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название марки', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StampMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название марки', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetalInstance',
            fields=[
                ('id', models.IntegerField(default=None, help_text='Введите id для этого вида металла', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(default=None, help_text='Количество металла')),
                ('status', models.CharField(blank=True, choices=[('д', 'доступно'), ('з', 'зарезервированно'), ('о', 'отсутствует')], default='о', help_text='Доступность металла', max_length=1)),
                ('metal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.metal')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='metal',
            name='stamp',
            field=models.ForeignKey(help_text='Выберите марку металла', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.stampmetal'),
        ),
        migrations.CreateModel(
            name='CementInstance',
            fields=[
                ('id', models.IntegerField(default=None, help_text='Введите id для этого вида цемента', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(default=None, help_text='Количество цемента')),
                ('status', models.CharField(blank=True, choices=[('д', 'доступно'), ('з', 'зарезервированно'), ('о', 'отсутствует')], default='о', help_text='Доступность цемента', max_length=1)),
                ('cement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cement')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='cement',
            name='stamp',
            field=models.ForeignKey(help_text='Выберите марку цемента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.stampcement'),
        ),
    ]
