# Generated by Django 4.0.3 on 2022-04-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cement_metal_stampcement_stampmetal_metalinstance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lumber',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='lumber',
            old_name='types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='metal',
            old_name='sizes',
            new_name='size',
        ),
    ]
