# Generated by Django 4.0.3 on 2022-04-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_sizes_lumber_size_rename_types_lumber_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumber',
            options={'ordering': ['type']},
        ),
    ]
