# Generated by Django 4.0.3 on 2022-04-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_lumber_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='summary',
        ),
    ]
