# Generated by Django 4.0.3 on 2022-05-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_variety_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lumberinstance',
            options={'ordering': ['type']},
        ),
        migrations.RemoveField(
            model_name='lumber',
            name='type',
        ),
        migrations.AddField(
            model_name='lumberinstance',
            name='type',
            field=models.ForeignKey(help_text='Выберите сорт пиломатериала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.types'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(help_text='Введите сорт пиломатериала', max_length=100),
        ),
    ]
