# Generated by Django 4.0.3 on 2022-05-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_lumber_options_alter_lumberinstance_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
