# Generated by Django 4.0.3 on 2022-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_types_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='summary',
            field=models.TextField(help_text='Введите описание сорта', max_length=500, null=True),
        ),
    ]
