# Generated by Django 4.0.3 on 2022-05-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_type_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cementinstance',
            options={'ordering': ['id']},
        ),
    ]
