# Generated by Django 4.0.3 on 2022-05-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_cementinstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='title',
        ),
    ]
