# Generated by Django 4.0.3 on 2022-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_rename_name_type_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcement',
            name='summary',
            field=models.TextField(help_text='Введите описание марки', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stampmetal',
            name='summary',
            field=models.TextField(help_text='Введите описание марки', max_length=500, null=True),
        ),
    ]
