# Generated by Django 4.0.3 on 2022-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_stampcement_summary_stampmetal_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='width',
        ),
        migrations.AddField(
            model_name='cement',
            name='gost',
            field=models.CharField(help_text='Введите ГОСТ металла', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lumber',
            name='gost',
            field=models.CharField(help_text='Введите ГОСТ металла', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='metal',
            name='gost',
            field=models.CharField(help_text='Введите ГОСТ металла', max_length=50, null=True),
        ),
    ]
