# Generated by Django 4.0.3 on 2022-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_metal_width_cement_gost_lumber_gost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumberinstance',
            name='Lumber_Photo',
            field=models.ImageField(null=True, upload_to='lesotorgov_base_site/catalog/templates/catalog/static/image'),
        ),
    ]
