# Generated by Django 4.0.3 on 2022-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_cementinstance_lumber_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cementinstance',
            old_name='Lumber_Photo',
            new_name='Cement_Photo',
        ),
        migrations.RenameField(
            model_name='metalinstance',
            old_name='Lumber_Photo',
            new_name='Metal_Photo',
        ),
    ]
