# Generated by Django 4.0.3 on 2022-05-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_lumberinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumberinstance',
            options={'ordering': ['due_back']},
        ),
    ]
