# Generated by Django 4.0.3 on 2022-05-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_lumberinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumberinstance',
            options={'ordering': ['type']},
        ),
        migrations.RemoveField(
            model_name='lumber',
            name='type',
        ),
        migrations.AddField(
            model_name='lumberinstance',
            name='type',
            field=models.ForeignKey(help_text='Выберите сорт пиломатериала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type'),
        ),
    ]
