# Generated by Django 4.0.3 on 2022-05-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_lumberinstance_options_remove_lumber_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='type',
            field=models.ForeignKey(help_text='Выберите сорт пиломатериала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type'),
        ),
    ]
