# Generated by Django 4.0.3 on 2022-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_cementinstance_cement_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementinstance',
            name='count',
            field=models.CharField(default=None, help_text='Количество цемента', max_length=10),
        ),
        migrations.AlterField(
            model_name='lumberinstance',
            name='count',
            field=models.CharField(default=None, help_text='Количество пиломатериала', max_length=10),
        ),
        migrations.AlterField(
            model_name='metalinstance',
            name='count',
            field=models.CharField(default=None, help_text='Количество металла', max_length=10),
        ),
    ]
