# Generated by Django 4.0.3 on 2022-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_cementinstance_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='img',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
